name: My First CI Pipeline

on: [push]

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check python Version
        run: python3 --version

      - name: Run a "Test"
        run: |
          echo "Testing logic..."
          if [ 1 -eq 1 ]; then
           echo " Math works! Test passed."
           exit 0
          else
           echo "Math is broken."
           exit 1
          fi
    
